name: Semantic release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    container: buildpack-deps:jammy-scm
    steps:
      - name: "Install and Configure applications"
        run: |
          apt-get update
          apt-get install -yqq --no-install-recommends \
            nodejs \
            npm
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fix repo
        run: |
          git status || git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: "Release"
        uses: cycjimmy/semantic-release-action@v4
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 23.0.0
          extra_plugins: |
            @semantic-release/commit-analyzer@11.1.0
            @semantic-release/exec@6.0.3
            conventional-changelog-conventionalcommits@7.0.2
      - name: Push new tag
        if: ${{ steps.version.outputs.new_release_published == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -f "v${{ steps.version.outputs.new_release_major_version }}"
          git push origin "v${{ steps.version.outputs.new_release_major_version }}" --force

    outputs:
      release_version: ${{ steps.version.outputs.new_release_version }}
